### PR TITLE
fixed wrapper

### PR DESCRIPTION
**Pull request by cdietrich**
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Review by kthoms — APPROVED** [review]

**Comment by cdietrich** [comment]
@kthoms  can this be tested somehow?

**Comment by kthoms** [comment]
> @kthoms can this be tested somehow?

Executing `./gradlew build`, or do you mean?

**Comment by cdietrich** [comment]
yes executing it locally to see if it works? or is this not possible cause sonatype etc

**Comment by kthoms** [comment]
Yes, the gradlew command from this branch executes on macOS.

**Pull request merged**
